config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("soundify.urls")),
]

soundify/urls.py
from os import name
from django.shortcuts import render
from . import views
from django.urls import path

app_name = "soundify"

urlpatterns = [
    path('', views.index_page_view, name='index'),
    path('index.html', views.index_page_view, name="index"),
    path('search.html', views.search_page_view, name='search'), 
    path('register.html', views.register_page_view, name="register"),
    path('feedback.html', views.feedback_page_view, name="feedback"),
    path('sections/login.html', views.login_page_view, name='login'),
    path('login.html', views.login_page_view, name='login'),
    path('logout', views.logout_page_view, name='logout'),
    path('user.html', views.user_page_view, name='user'),
    path('contacto.html', views.contacto_page_view, name='contacto'),
    path('novo_contacto.html', views.novo_contacto_view, name='novo'),
    path('edita_contacto.html/<int:contacto_id>', views.edita_contacto_view, name='edita'),
    path('apaga/<int:contacto_id>', views.apaga_contacto_view, name='apaga'),
    path('quizz.html', views.quizz_page_view, name='quizz'),
    path('comentarios.html', views.comentarios_page_view, name='comentarios'),
    path('sections/<int:num>', views.section, name='section'),
]

soundify/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    password = models.CharField(max_length=32)
    email = models.EmailField(max_length=32)

    def __str__(self):
        return f"{self.name} is {self.username}: {self.email}"


class Music(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    duration = models.IntegerField()
    genre = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.user} uploaded {self.name}: {self.duration} ({self.genre})"

class Playlist(models.Model):
    name = models.ManyToManyField(Music, blank=True)
    user = ForeignKey(User, on_delete=models.CASCADE)
    genre = models.CharField(max_length=64)

    def __str__(self):
        return f"Playlist {self.name}: {self.user} -> {self.genre}"
    
class Contacto(models.Model):
    contacto_id = models.IntegerField()
    nome = models.CharField(max_length=64)
    apelido = models.CharField(max_length=64)
    telefone = models.CharField(max_length=32)
    email = models.EmailField(max_length=32)
    dataNascimento = models.DateField()

    def __str__(self):
        return f"Contacto: {self.contacto_id}, {self.nome} {self.apelido} ({self.telefone}) com {self.email} nascido em {self.dataNascimento}"

class Quizz(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    resposta1 = models.CharField(max_length=32, blank=True)
    resposta2 = models.CharField(max_length=32, blank=True)
    resposta3 = models.CharField(max_length=32, blank=True)
    resposta4 = models.CharField(max_length=32, blank=True)
    resposta5 = models.CharField(max_length=32, blank=True)
    resposta6 = models.CharField(max_length=32, blank=True)
    resposta7 = models.CharField(max_length=32, blank=True)
    resposta8 = models.CharField(max_length=32, blank=True)
    resposta9 = models.CharField(max_length=32, blank=True)
    resposta10 = models.CharField(max_length=32, blank=True)


    def __str__(self):
        return f"User: {self.user}"

class Comentario(models.Model):
    user = models.CharField(max_length=64)
    comentario = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return f"O user {self.user} comentou o seguinte {self.comentario}"

soundify/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm, widgets
from .models import Contacto

class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'apelido': forms.TextInput(attrs={'class': 'form-control'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'dataNascimento': forms.DateInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'nome': 'Nome',
            'apelido': 'Apelido',
            'telefone': 'Telefone',
            'email': 'Email',
            'dataNascimento': 'Data de Nascimento',
        }

soundify/views.py
from django.http.response import Http404, HttpResponse
from .models import Contacto, Quizz, Comentario
from .forms import ContactoForm
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import login, logout, authenticate


# Create your views here.
def index_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    return render(request, "soundify/index.html")

def search_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    return render(request, "soundify/search.html")

def register_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    return render(request, 'soundify/register.html')

def feedback_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    return render(request, 'soundify/feedback.html')
"""
def index_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    #return render(request, "soundify/user.html")
    return render(request, "soundify/index.html")
"""
def user_page_view(request):
    return render(request, "soundify/user.html")

def login_page_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect("user.html")

        else:
            return render(request, "soundify/login.html", {"message": "Invalid credentials."})

    return render(request, "soundify/login.html")

def logout_page_view(request):
    logout(request)
    return render(request, "soundify/login.html", {"message": "Logged out."})

def contacto_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")

    context = {'contactos': Contacto.objects.all()}
    return render(request, 'soundify/contacto.html', context)

def novo_contacto_view(request):
    form = ContactoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('soundify:contacto'))
    context = {'form': form}
    return render(request, "soundify/novo_contacto.html", context)

def edita_contacto_view(request, contacto_id):
    contacto = Contacto.objects.get(contacto_id=contacto_id)
    form = ContactoForm(request.POST or None, instance=contacto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('soundify:contacto'))

    context = {'form': form, 'contacto_id': contacto_id, 'contacto': contacto}
    return render(request, "soundify/edita_contacto.html", context)

def apaga_contacto_view(request, contacto_id):
    Contacto.objects.get(contacto_id=contacto_id).delete()
    return HttpResponseRedirect(reverse('soundify:contacto'))

def quizz_page_view(request):
    if not request.user.is_authenticated:
            return HttpResponseRedirect("login.html")
    """
    if request.method == "POST":
        form = QuizzForm(request.POST or None)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('soundify:resultados'))

        context = {'form': form}
        return render(request, "soundify/quizz.html", context)

    form = QuizzForm(None)
    """

    anwsers = {
        'pergunta1': 'rap',
        'pergunta2': 'cleveland ohio',
        'pergunta3': 'the weeknd',
        'pergunta4': 'masked wolf',
        'pergunta5': 'astronaut in the ocean masked wolf',
        'pergunta6': 'olivia rodrigo',
        'pergunta7': 'justin bieber',
        'pergunta8': 'the weeknd',
        'pergunta9': 'bliding lights',
        'pergunta10': 'justin bieber',
    }

    if request.method == "POST":
        # cada pergunta vale dois pontos
        pontos_globais = 0

        for pergunta in anwsers:
            if(request.POST[pergunta] == anwsers[pergunta]):
                pontos_globais += 2

        return render(request, "soundify/resultados.html", {'pontos_globais': pontos_globais, 'user': request.user})

    return render(request, "soundify/quizz.html")

def comentarios_page_view(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")

    if request.method == "POST":
        new_comentario = Comentario(user=request.user, comentario=request.POST['comentario'])
        new_comentario.save()

    return render(request, "soundify/comentarios.html")

def section(request, num):
    if not request.user.is_authenticated:
        return HttpResponseRedirect("login.html")
    
    pages = [
        "index.html",
        "search.html",
        "quizz.html",
        "comentarios.html",
        "contactos.html",
        "login.html",
        "logout.html",
        "register.html",
    ]

    pages_dict = {
        "index.html": index_page_view(request),
        "search.html": search_page_view(request),
        "quizz.html": quizz_page_view(request),
        "comentarios.html": comentarios_page_view(request),
        "contactos.html": contacto_page_view(request),
        "login.html": login_page_view(request),
        "logout.html": logout_page_view(request),
        "register.html": register_page_view(request),
    }

    if 1 <= num <= 8:
        key = pages[num -1]
        return HttpResponse(pages_dict[key])        
        return 
    else:
        raise Http404("No such section")

soundify/templates/soundify/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="music">
        <meta name="keywords" content="HTML, CSS, Music, Genre">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="shortcut icon" type="images/logo-project" href="{% static "soundify/images/logo-project.ico" %}"/>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Londrina+Solid&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'soundify/css/base.css' %}">
        <title>Soundify</title>
        <script src="{% static 'soundify/js/index.js' %}"></script>
    </head>
    <body>
        <nav class="main-nav">
            <ul>
                <li><a href="{% url "soundify:index" %}" class="home" data-section="1">Soundify</a></li>
                <li><a href="{% url "soundify:search" %}" class="search" data-section="2"><span class="material-icons">&#xe8b6;</span></a></li>
                <li><a href="{% url "soundify:quizz" %}" class="quizz" data-section="3">Quizz</a></li>
                <li><a href="{% url "soundify:comentarios" %}" class="comentarios" data-section="4">Comentários</a></li>
                <li><a href="{% url "soundify:contacto" %}" class="contacto" data-section="5">Contactos</a></li>
                <li><a href="{% url "soundify:login" %}" class="login" data-section="6">Log In</a></li>
                <li><a href="{% url "soundify:logout" %}" class="logout" data-section="7">Logout</a></li>
                <li><a href="{% url "soundify:register" %}" class="register-button" data-section="8">Register for FREE</a></li>
            </ul>
        </nav>
        <main id="main-content">
            {% block main %}
            {% endblock main %}
        </main>        
        <footer>
            <div id="developed-authors"><p>Developed by some damn good programmers</p></div>
            <img src="{% static "soundify/images/iconfinder_Rounded_Facebook_svg_5282541.png" %}" width="30px" height="25">
            <img src="{% static "soundify/images/iconfinder_Rounded_Instagram_svg_5282544.png" %}" width="30px" height="25">
            <img src="{% static "soundify/images/iconfinder_Rounded_Twitter5_svg_5282551.png" %}" width="30px" height="25">
            <img src="{% static "soundify/images/iconfinder_Rounded_Linkedin2_svg_5282542.png" %}" width="30px" height="25">
        </footer>
    </body>
</html>

soundify/templates/soundify/comentarios.html
{% extends "soundify/base.html" %}

{% block main %}
    <section class="comentarios-container">
        <form action="{% url 'soundify:comentarios' %}" method="POST">
            {% csrf_token %}

            <h3 class="comentarios-header">Adicione o seu comentário aqui</h3>
        
            <label for="comentario">Comente aqui:</label>
            <input type="text" name="comentario" id="comentario">

            <input type="submit" value="Submeter">
        </form>
    </section>

{% endblock %}

soundify/templates/soundify/contacto.html
{% extends "soundify/base.html" %}

{% block main %}

    <section class="container-contacto">
        <h2 class="contacto-header-main">Contactos</h2>

        {% for contacto in contactos %}
            <p class="contactos-p">
                {{ contacto.nome }} {{contacto.apelido}} ({{contacto.email}})
                <a href="{% url 'soundify:edita' contacto.contacto_id %}" class="btn btn-warning">Editar</a>
            </p>
        {% endfor %}

        <a href="{% url 'soundify:novo' %}" class="btn-novo-contacto">Novo Contacto</a>
    </section>

{% endblock %}

soundify/templates/soundify/edita_contacto.html
{% extends "soundify/base.html" %}

{% block main %}
    <section class="edita-contacto-container">
        <h2>Contacto</h2>
        <!--action devia ter isto {% url 'soundify:edita' contacto.contacto_id %} mas nao funciona se tiver-->
        <form action="{% url 'soundify:edita' contacto.contacto_id %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}

            <a href="{% url 'soundify:contacto' %}" role="button" class="btn btn-warning">Cancelar</a>
            <input type="submit" value="Gravar" class="btn btn-success" >
            <a href="{% url 'soundify:apaga' contacto_id %}" role="button" class="btn btn-danger">Apagar</a>

        </form>
    </section>

{% endblock %}

soundify/templates/soundify/feedback.html
{% extends "soundify/base.html" %}

{% load static %}

{% block main %}

<main class="tables-section">
    <iframe id="iframe-video" width="560" height="315" src="https://www.youtube.com/embed/2SDvdsV3vXQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <h2 class="html-header">Html</h2>
    <table border="1" cellpading="10%" cellspacing="5%" style="margin: auto;" class="html-table">
        <tr>
            <td>Headers</td>
            <td>h2, h4</td>
        </tr>
        <tr>
            <td>Marcadores</td>
            <td>Header, Nav, Section, Footer</td>
        </tr>
        <tr>
            <td>Atributos</td>
            <td>src, alt, type, id, border, cellpading, cellspacing, style, href, target</td>
        </tr>
    </table>
    <h2 class="css-header">Css</h2>
    <table border="1" cellpading="10%" cellspacing="5%" style="margin: auto;" class="css-table">
        <tr>
            <td>Tipos de Seletores</td>
            <td>Universal, Tipo, Classe, Id, Atributo, Pseudo-classe, Pseudo-elemnto</td>
        </tr>
        <tr>
            <td>Combinadores de Seletores</td>
            <td>Descendentes, Filhos, Adjacentes, Agrupados</td>
        </tr>
        <tr>
            <td>Unidades</td>
            <td>%, px, em</td>
        </tr>
    </table>
    <h2 class="css-header">Django</h2>
    <table border="1" cellpading="10%" cellspacing="5%" style="margin: auto;" class="css-table">       
        <tr>
            <td>Mapeamento Objeto-Relacional (ORM)</td>
            <td>Com o ORM do Django você define a modelagem de dados através de classes em Python. Com isso é possível gerar suas tabelas no banco de dados e manipulá-las sem necessidade de utilizar SQL (o que também é possível).</td>
        </tr>
        <tr>
            <td>Interface Administrativa</td>
            <td>No Django é possível gerar automaticamente uma interface para administração dos modelos criados através do ORM.</td>
        </tr>
        <tr>
            <td>Formulários</td>
            <td>É possível gerar formulários automaticamente através dos modelos de dados.</td>
        </tr>
        <tr>
            <td>URLs</td>
            <td>No Django não há limitações para criação de URLs de maneira simples.</td>
        </tr>
        <tr>
            <td>Sistema de Templates</td>
            <td>O Django tem uma linguagem de templates poderosa, extensível e amigável. Com ela você pode separar design, conteúdo e código em Python.</td>
        </tr>
        <tr>
            <td>Sistema de Cache</td>                
            <td>O Django possui um sistema de cache que se integra ao memcached ou em outros frameworks de cache.</td>
        </tr>
        <tr>
            <td>Internacionalização</td>
            <td>Django tem total suporte para aplicações multi-idioma, deixando você especificar strings de tradução e fornecendo ganchos para funcionalidades específicas do idioma</td>
        </tr>
    </table>
        <h2 class="css-header">JavaScript</h2>
        <table border="1" cellpading="10%" cellspacing="5%" style="margin: auto;" class="css-table">
            <tr>
                <td>Programação Orientada a Eventos</td>
                <td>Uma característica do JavaScript que o torna útil para a programação web é que suporta Programação Orientada a Eventos é, a sua deteção de eventos (eventlistener) e em ações que devem ser tomadas
                    quando um evento é detetado (eventhandler)</td>
            </tr>
            <tr>
                <td>Variáveis</td>
                <td>Existem três palavras-chave que podemos usar para atribuir valores em JavaScript: o var, o let e o const.
                </td>
            </tr>
            <tr>
                <td>Data-attributes e datasets</td>
                <td>Podemos criar novos atributos com data-attributes, que começam com data-* com a informação que queremos.</td>
            </tr>
            <tr>
                <td>Manipulação do DOM</td>
                <td>O Modelo de Documento por Objetos (do inglês Document Object Model - DOM) é uma convenção multiplataforma e independente de linguagem de programação, fiscalizada pelo entidade World Wide Web Consortium (W3C), para representação e interação com objetos em documentos HTML, XHTML e, XML.</td>
            </tr>
            <tr>
                <td>Local Storage</td>
                <td>Quando se recarrega uma página, toda a informação é perdida.
                    </td>
            </tr>
            <tr>
                <td>API</td>
                <td>Objetos JavaScript servem para transferir dados de um   site para outro, particularmente quando se utilizam APIs</td>
            </tr>
            <tr>
                <td>AJAX</td>
                <td>Usamos AJAX (Assincronous JavaScript and XML), que permite aceder a informações de páginas externas.</td>
            </tr>
        </table>
</main>
<section class="section-wordcloud">
    <figure class="figure-wordcloud">
        <img src="{% static "soundify/images/wordcloud.jpg" %}" width="450px">
    </figure>
    <details id="details-wordcloud"><summary></summary>Wordcloud</details>
    <figure class="figure-wordcloud">
        <img src="{% static 'soundify/images/tree.jfif' %}" width="450px">
    </figure>
    <details id="details-wordcloud"><summary></summary>Mapa do Website</details>
</section>
<section class="feedback-section">
    <h2 class="feedback-header">Let us know what you think!</h2>
    <p class="feedback-p">Your opinion is very important to us so you can help us improve our services.</p>
    <div class="rate-us">
        <h4 class="rate-us-header">Click a star to rate our services</h4>
        <div class="rate-us-star">
            <span class="material-icons">&#xe885;</span>
            <span class="material-icons">&#xe885;</span>
            <span class="material-icons">&#xe885;</span>
            <span class="material-icons">&#xe885;</span>
            <span class="material-icons">&#xe885;</span>
        </div>
    </div>
</section>            

{% endblock %}

soundify/templates/soundify/formulario.html
{% extends "soundify/base.html" %}

{% block main %}

    <h1>Contacto</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'soundify:contacto' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-sucess">

    </form>

{% endblock %}

soundify/templates/soundify/index.html
{% extends "soundify/base.html" %}

{% load static %}

{% block main %}

<div class="image-container">
    <img src="{% static 'soundify/images/festival-image.jpeg' %}" class="image-container-src">
    <div class="image-container-2"></div>
</div>
<div>
    <a href="{% url "soundify:feedback" %}" id="header-blur-image">Soundify</a>
</div>
<section class="main-section">
    <figure>
        <img src="{% static "soundify/images/logo-project.png" %}" alt="soundify logo" id="main-section-logo">
    </figure>
    <div class="main-section-content">
        <p id="main-section-phrase">The newest music web aplication</p>
        <p id="main-section-quote">“Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything.” – Plato</p>
    </div>
</section>

{% endblock  %}

soundify/templates/soundify/login.html
{% extends "soundify/base.html" %}

{% block main %}
<main class="login-section">

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form class="login-form" action="{% url 'soundify:login' %}" method="POST">
        {% csrf_token %}
        <fieldset class="login-fieldset">
            <div class="user-pass">
                <input type="text" name="username" required maxlength="25">
                <span></span>
                <label>Username</label>
            </div>
            <div class="user-pass">
                <input type="password" name="password" required minlength="8">
                <span></span>
                <label>Password</label>
            </div>
            <div class="forgot-pass">Forgot password?</div>
            <input type="submit" value="Log in">
            <div class="signup">Not member? <a href="{% url 'soundify:register' %}">Signup</a></div>
        </fieldset>
    </form>
</main>

{% endblock %}

soundify/templates/soundify/novo_contacto.html
{% extends "soundify/base.html" %}

{% block main %}
    <section class="novo-contacto-container">
        <h1 class="contacto-header-main">Contacto</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <a href="{% url 'soundify:contacto' %}" class="btn btn-warning">Cancelar</a>
            <input type="submit" value="Gravar" class="btn btn-sucess">

        </form>
    </section>

{% endblock %}

soundify/templates/soundify/quizz.html
{% extends "soundify/base.html" %}

{% block main %}

<section class="quizz-container">
    <h1 class="quizz-header-main">Quizz</h1>
    <form action="{% url 'soundify:quizz' %}" method="POST">
        {% csrf_token %} 
        
        <label>Masked wolf faz que tipo de musica?</label>
        <input type="text" name="pergunta1" class="perguntas">

        <label>DaBaby é originalmente de onde?</label>
        <input type="text" name="pergunta2" class="perguntas">

        <label>Quem lançou o album After Hours?</label>
        <input type="text" name="pergunta3" class="perguntas">

        <label>Qual o artista menos conhecido?</label>
        <input type="text" name="pergunta4" class="perguntas">

        <label>Qual a musica com menos visualizações?</label>
        <input type="text" name="pergunta5" class="perguntas">

        <label>Quem mais recentemente destes artistas lançou um album?</label>
        <input type="text" name="pergunta6" class="perguntas">

        <label>Qual o artista presente na lista que começou a sua carreira musical aos 15/16 anos?</label>
        <input type="text" name="pergunta7" class="perguntas">

        <label>Qual o artista mais conhecido?</label>
        <input type="text" name="pergunta8" class="perguntas">

        <label>Qual a musica com mais visualizações?</label>
        <input type="text" name="pergunta9" class="perguntas">

        <label>Qual o artista com mais subscritores no youtube?</label>
        <input type="text" name="pergunta10" class="perguntas">

        <input type="submit" value="Submeter" class="btn btn-sucess">

    </form>
</section>


{% endblock %}

soundify/templates/soundify/register.html
{% extends "soundify/base.html" %}

{% block main %}

<main class="register-section">
    <form class="register-form">
        <fieldset class="register-fieldset">
            <div class="user-pass">
                <input type="text" required maxlength="25">
                <span></span>
                <label>Username</label>
            </div>
            <div class="user-pass">
                <input type="email" required>
                <span></span>
                <label>Email</label>
            </div>
            <div class="user-pass">
                <input type="password" required minlength="8">
                <span></span>
                <label>Password</label>
            </div>
            <div class="user-pass">
                <input type="password" required minlength="8">
                <span></span>
                <label>Repeat Password</label>
            </div>
            <div class="checkbox-terms-condition">
                <input type="checkbox" required>
                <span id="terms-condition">I agree to the Terms & Condition</span>
            </div>
            <input type="submit" value="Register">
        </fieldset>
    </form>
</main>

{% endblock %}

soundify/templates/soundify/resultados.html
{% extends "soundify/base.html" %}

{% block main %}

    <section class="resultados-container">
        <h1 class="resultados-header">Congratulations!</h1>

        <div class="resultados-points">
            {{user}} got {{pontos_globais}} points out of 20 points!
        </div>
    </section>

{% endblock %}

soundify/templates/soundify/user.html
{% extends "soundify/base.html" %}

{% block main %}

<main id="user-container">
    <h1>Welcome, {{ request.user.username }}</h1>

    <p>Username: {{ request.user.username }}</p>
    <p>Email: {{ request.user.email }}</p>
    <a href="{% url 'soundify:logout' %}" id="logout-user-button">Log Out</a>
</main>

{% endblock %}